games/urls.py
from django.conf.urls import include, patterns, url

urlpatterns = patterns('games.views',
    url('^$', 'index', name='index'),
    url(r'^create/$', 'create', name='create'),
    url('^(?P<game_id>\d+)/$', 'show', name='show'),
)

multiverse_sidekick/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'multiverse_sidekick.views.home', name='home'),
    url(r'^games/', include('games.urls', namespace='games'), name='games'),

    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

multiverse_sidekick/views.py
from django.shortcuts import render

from heroes.models import Hero


def home(request):
    max_heroes = Hero.objects.count()
    context = {
        'max_heroes': range(1, max_heroes-1),
    }
    print context
    return render(
        request,
        'home/index.html',
        context,
    )

multiverse_sidekick/templates/home/index.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'games:index' %}">List of games</a>

<form action="{% url 'games:create' %}" method="get">
  <select name="num_heroes">
  {% for i in max_heroes %}
    <option value="{{ i }}" {% if i == 3 %}selected{% endif %}>{{ i }}</option>
  {% endfor %}
  </select>
  <input type="submit" name="custom" value="Custom" />
  <input type="submit" name="random" value="Random" />
</form>

{% endblock %}